### ISSUE TITLE
Join button has Weird styling. 

### ISSUE THREAD

**Issue by sridhar-5** [sridhar-5/Google-Meet-Clone#2]
check the image attached below for the weird Join button styling. 

@radiantly issue for you.

<img width="1792" alt="Screenshot 2021-07-13 at 6 47 03 PM" src="https://user-images.githubusercontent.com/65086710/125459388-b1930b13-f0e2-4ad2-94a3-f89c6fc59a54.png">

**Comment by radiantly** [comment]
:+1:
